### ISSUE TITLE
I have trouble creating a Pico Blog

### ISSUE THREAD

**Issue by AlexL777** [mcbSolutions/Pico-Plugins#3]
Hello Developers,

I have only one problem with creating Pico blog. I can not understand which files in the **/content/blog** must be.

I installed the blog plugin and under **/blog** I have nothing yet.

**Comment by mcbSolutions** [comment]
Hi,

are you using Pico 1.0? I have not tested it for 1.0 at the moment.

A must have for the content is the `Date: 2013-10-28` in the meta section.

best regards, Mike

**Comment by mcbSolutions** [comment]
Hi,

the plugin goes to the `plugin` folder. The blogs content to `content/blog/`

**Comment by ghost** [comment]
I have to get back to you, because I started the new Pico CMS project with the last Pico version.

Now I have the blog at http://picocms.wpzweinull.ch/blog/index, but the shortcode is still to be seen and is not generated to the blog content.

How can I fix it.

Or have you had the blog plugin in the last Pico CMS version in the test had?

I would also like to know how I can exclude the blog posts from `/content/blog` in the website navigation.

The one blogpost is shown with me under https://picocms.wpzweinull.ch in the left navi and I would like to exclude.

Then I hope that you will report here soon.

Thanks in advance.

Alexander

**Comment by mcbSolutions** [comment]
This task is closed. Your question refers to [Warning: DOMDocument::loadHTML()...](https://github.com/mcbSolutions/Pico-Plugins/issues/4)

[Check this out](https://validator.w3.org/nu/?doc=http%3A%2F%2Fpicocms.wpzweinull.ch%2Fblog%2Findex); I think this will solve your problem.

![w3c](https://user-images.githubusercontent.com/5785952/30268451-07766f98-96e6-11e7-827b-c8e14cbfc723.png)
